# .cirrus.yml - Android (Linux) example for Cirrus CI

# Top-level environment variables
env:
  ANDROID_SDK_ROOT: /opt/android-sdk
  ANDROID_HOME: /opt/android-sdk
  GRADLE_USER_HOME: $CIRRUS_WORKING_DIR/.gradle

task:
  name: android-linux-build
  # Use a reasonably recent Ubuntu image
  container:
    image: ubuntu:22.04
    cpu: 8
    memory: 32G
  #env:
    #- CIRRUS_WORKING_DIR=/tmp/build
    #- ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}
    #- GRADLE_USER_HOME=${GRADLE_USER_HOME}
  # Cache Gradle and Android SDK to speed up consecutive runs
  # Setup steps and build commands
  script:
    # Basic system deps
    - set -ex
    - apt update
    - DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt -y install php-cli php-xml php-json libelf-dev build-essential libelf-dev libncurses-dev libssl-dev bc flex bison libxml2-dev uuid-dev elfutils liblz4-tool liblzma-dev zlib1g-dev cpio gawk git zip unzip php-zip wget
    - git clone https://github.com/Automattic/pocket-casts-android.git
    - ./gradlew :app:assembleDebugProd 
