# .cirrus.yml
task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma

  task:
    script: echo "Hello World from macOS!"


  name: macos-build-and-test
  container:
    image: macos  # note: Cirrus doesn't use Docker for macOS. Use osx_instance below.
  osx_instance:
    image: macos-12
  script:
    - echo "Install dependencies"
    - brew update
    - brew install cocoapods # example
    - pod install
    - echo "Run build"
    - xcodebuild -workspace MyApp.xcworkspace -scheme MyApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' build test
  artifacts:
    - path: build/reports
      name: test-reports
