container:
  image: ghcr.io/cirruslabs/android-sdk:35
  cpu: 8
  memory: 32G

task:
  setup_script:
  - sudo apt update
  - sudo apt install openjdk-17-jdk -y

  git_clone_script:
  - git clone https://github.com/Automattic/pocket-casts-android

  android_build_script:
  - cd pocket-casts-android
  - ./gradlew --no-daemon assembleRelease --stacktrace
  
