on:
  push:
    branches:
      - main

jobs:
  macos:
    name: "Run on mac"
    runs-on: namespace-profile-agi
    steps:
      - uses: actions/checkout@v4
      - name: List Installed Xcodes
        run: xcodes installed
      - name: Select Xcode 16.2
        run: sudo xcodes select 16.2

  macos_correct:
    name: "Run on mac"
    runs-on: namespace-profile-macos
    steps:
      - uses: actions/checkout@v4
      - name: List Installed Xcodes
        run: xcodes installed
      - name: Select Xcode 16.2
        run: sudo xcodes select 16.2

  linux-x86:
    name: "Run on linux"
    runs-on: ghcr.io/cirruslabs/ubuntu-runner-amd64:24.04-md
    steps:
      - uses: actions/checkout@v4
      - name: Hello
        run: |
          set -e
          echo "Hello again"
          
  measure:
    runs-on: macos-latest
    steps:
      - name: Start marker
        run: date -u +"START %Y-%m-%dT%H:%M:%SZ"
      - name: Sleep 10 minutes
        run: sleep 600
      - name: End marker
        run: date -u +"END %Y-%m-%dT%H:%M:%SZ"
