on:
  push:
    branches:
      - main

jobs:
  macos:
    name: "Run on mac"
    runs-on: ghcr.io/cirruslabs/macos-runner:sequoia
    steps:
      - uses: actions/checkout@v4
      - name: List Installed Xcodes
        run: xcodes installed
      - name: Select Xcode 16.2
        run: sudo xcodes select 16.2

  linux-x86:
    name: "Run on linux"
    runs-on: ghcr.io/cirruslabs/ubuntu-runner-amd64:24.04-md
    steps:
      - uses: actions/checkout@v4
      - name: Hello
        run: |
          set -e
          echo "Hello again"
